export enum MemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum LevelName {
  ESTANDAR = 'ESTANDAR',
  PREMIUM = 'PREMIUM',
  GOLDEN = 'GOLDEN',
}

export enum BenefitType {
  DISCOUNT_TICKET = 'DISCOUNT_TICKET',
  DISCOUNT_CANDY = 'DISCOUNT_CANDY',
  AVANT_PREMIERE = 'AVANT_PREMIERE',
  PREMIUM_ROOM = 'PREMIUM_ROOM',
  MERCHANDISE = 'MERCHANDISE',
  POINTS_REDEMPTION = 'POINTS_REDEMPTION',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum TransactionType {
  PURCHASE_TICKET = 'PURCHASE_TICKET',
  PURCHASE_CANDY = 'PURCHASE_CANDY',
  REDEMPTION = 'REDEMPTION',
  ADJUSTMENT = 'ADJUSTMENT',
  POINTS_EXPIRY = 'POINTS_EXPIRY',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum TransactionOrigin {
  WEB = 'WEB',
  POS = 'POS',
}

export enum RedemptionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum UserRole {
  CLIENTE = 'CLIENTE',
  CAJERO = 'CAJERO',
  ADMINISTRADOR = 'ADMINISTRADOR',
}

export enum NotificationType {
  POINTS_EARNED = 'POINTS_EARNED',
  LEVEL_PROGRESS = 'LEVEL_PROGRESS',
  LEVEL_UPGRADE = 'LEVEL_UPGRADE',
  BENEFIT_AVAILABLE = 'BENEFIT_AVAILABLE',
  MERCHANDISE_DELIVERY = 'MERCHANDISE_DELIVERY',
  WELCOME = 'WELCOME',
  POINTS_EXPIRY_WARNING = 'POINTS_EXPIRY_WARNING',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LEVEL_UPGRADE = 'LEVEL_UPGRADE',
  POINTS_ADJUSTMENT = 'POINTS_ADJUSTMENT',
  REDEMPTION = 'REDEMPTION',
  CONFIG_CHANGE = 'CONFIG_CHANGE',
}
